// Mocks generated by Mockito 5.0.13 from annotations
// in best_wordpress_sites/test/home/data/repositories/templates_repository_impl_test.dart.
// Do not manually edit this file.

import 'package:best_wordpress_sites/home/data/datasources/templates_fixtures_datasource.dart'
    as _i2;
import 'package:best_wordpress_sites/home/domain/entities/template.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TemplatesFixturesDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplatesFixturesDatasource extends _i1.Mock
    implements _i2.TemplatesFixturesDatasource {
  MockTemplatesFixturesDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Template> getTemplates(List<Map<String, dynamic>>? templateData) =>
      (super.noSuchMethod(Invocation.method(#getTemplates, [templateData]),
          returnValue: <_i3.Template>[]) as List<_i3.Template>);
  @override
  String toString() => super.toString();
}
