// Mocks generated by Mockito 5.0.13 from annotations
// in best_wordpress_sites/test/home/domain/usecases/get_templates_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:best_wordpress_sites/home/domain/entities/template.dart' as _i4;
import 'package:best_wordpress_sites/home/domain/repositories/templates_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [TemplatesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplatesRepository extends _i1.Mock
    implements _i2.TemplatesRepository {
  MockTemplatesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Template>> getTemplates() =>
      (super.noSuchMethod(Invocation.method(#getTemplates, []),
              returnValue: Future<List<_i4.Template>>.value(<_i4.Template>[]))
          as _i3.Future<List<_i4.Template>>);
  @override
  String toString() => super.toString();
}
